### ISSUE TITLE
Unable to execute inference.py

### ISSUE THREAD

**Issue by akashjobanputra** [ildoonet/tf-openpose#14]
Executing the command mentioned in README.

`python3 inference.py --model=mobilenet --imgpath=<path-to-image>`

Gives this error in the end.

`Failed to get matching files on ./models\trained/mobilenet_368x368/model-release: Not found`

And there's nothing about Trained folder in README.md

**Comment by jobim3d** [comment]
I get this error too.

**Comment by mnaranjo** [comment]
Me too :-(

**Comment by strobmax** [comment]
- Download the `mobilenet 368x368` weights/checkpoint files (as linked in the readme)
- Adapt the paths in `networks.py` so that the downloaded files get restored (`loader.restore` should be called with something like `'[PATH_TO_DOWNLOADED_CHECKPOINT_FOLDER]/model-388003'` without any file extensions)

**Comment by jeyawn** [comment]
when i downloaded the models and modify the code, it still have errors;

2017-11-15 10:01:55.643782: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 375.66.0
2017-11-15 10:01:55.643788: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:300] kernel version seems to match DSO: 375.66.0
INFO:tensorflow:Restoring parameters from ./models/mobilenet_368x368/model-388003
2017-11-15 10:01:57,600 INFO Restoring parameters from ./models/mobilenet_368x368/model-388003
2017-11-15 10:01:57.856058: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage5_L2_2_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.860577: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage5_L2_3_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.863187: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage5_L2_4_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.864063: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage5_L2_5_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.865679: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage6_L1_1_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.867032: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage6_L1_2_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.868632: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage6_L1_3_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.869931: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage6_L1_4_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.871450: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage6_L1_5_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.873282: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage6_L2_1_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.874794: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage6_L2_2_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.878593: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage6_L2_3_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.879861: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage6_L2_4_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.882751: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage6_L2_5_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.885738: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key MobilenetV1/Conv2d_0/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.887116: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key MobilenetV1/Conv2d_10_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.888944: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage5_L2_1_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.889782: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key MobilenetV1/Conv2d_11_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.892116: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key MobilenetV1/Conv2d_2_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.893473: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key MobilenetV1/Conv2d_1_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.895517: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key MobilenetV1/Conv2d_3_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.898718: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key MobilenetV1/Conv2d_4_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.901610: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key MobilenetV1/Conv2d_5_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.902991: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key MobilenetV1/Conv2d_6_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.904798: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key MobilenetV1/Conv2d_7_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.906265: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage5_L1_5_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.908498: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key MobilenetV1/Conv2d_8_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.909199: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key MobilenetV1/Conv2d_9_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.915773: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage1_L1_1_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.919393: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage1_L1_3_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.920945: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage1_L1_4_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.921516: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage1_L1_5_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.922258: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage5_L1_4_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.923465: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage1_L2_1_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.925081: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage1_L1_2_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.925573: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage1_L2_2_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.926912: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage1_L2_3_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.927975: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage1_L2_4_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.930758: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage1_L2_5_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.933026: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage2_L1_1_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.935328: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage5_L1_3_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.935596: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage2_L1_2_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.937661: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage2_L1_3_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.940021: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage2_L1_4_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.942464: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage2_L1_5_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.943362: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage2_L2_1_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.947879: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage2_L2_2_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.952309: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage2_L2_3_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.956860: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage5_L1_2_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.958723: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage2_L2_4_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.960879: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage2_L2_5_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.962403: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage3_L1_1_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.964658: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage3_L1_2_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.966254: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage3_L1_3_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.966800: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage5_L1_1_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.966993: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage3_L1_4_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.969448: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage3_L1_5_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.970581: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage3_L2_1_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.973933: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage3_L2_2_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.973958: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage3_L2_3_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.975185: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage3_L2_4_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.975773: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage4_L2_5_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.977009: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage3_L2_5_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.979628: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage4_L1_1_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.982459: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage4_L1_2_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.984104: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage4_L1_3_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.985895: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage4_L1_4_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.987194: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage4_L1_5_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.992043: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage4_L2_1_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.992582: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage4_L2_4_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.994649: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage4_L2_2_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-15 10:01:57.995790: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key Openpose/MConv_Stage4_L2_3_pointwise/BatchNorm/gamma not found in checkpoint
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 1139, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 1121, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.4/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Key Openpose/MConv_Stage5_L2_2_pointwise/BatchNorm/gamma not found in checkpoint
         [[Node: save/RestoreV2_349 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_349/tensor_names, save/RestoreV2_349/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference.py", line 35, in <module>
    net, _, last_layer = get_network(args.model, input_node, sess)
  File "/dev/tf-openpose/networks.py", line 46, in get_network
    loader.restore(sess_for_load, os.path.join(_get_base_path(), ckpts[type]))
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/saver.py", line 1548, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key Openpose/MConv_Stage5_L2_2_pointwise/BatchNorm/gamma not found in checkpoint
         [[Node: save/RestoreV2_349 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_349/tensor_names, save/RestoreV2_349/shape_and_slices)]]

Caused by op 'save/RestoreV2_349', defined at:
  File "inference.py", line 35, in <module>
    net, _, last_layer = get_network(args.model, input_node, sess)
  File "/dev/tf-openpose/networks.py", line 45, in get_network
    loader = tf.train.Saver()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/saver.py", line 1139, in __init__
    self.build()
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/saver.py", line 1170, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 640, in restore_v2
    dtypes=dtypes, name=name)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Key Openpose/MConv_Stage5_L2_2_pointwise/BatchNorm/gamma not found in checkpoint
         [[Node: save/RestoreV2_349 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_349/tensor_names, save/RestoreV2_349/shape_and_slices)]]

**Comment by ildoonet** [comment]
Yes it is the problem related to the model file. you should download and move the file correctly.

**Comment by mnaranjo** [comment]
Hi,

I have followed the steps, but when I exec
`$ python3 inference.py --model=mobilenet --imgpath=...`

I get the next error:
`DataLossError (see above for traceback): Unable to open table file /home/Downloads/mobilenet/model-388003: Failed precondition: /home/Downloads/mobilenet/model-388003: perhaps your file is in a different file format and you need to use a different restore operator?`

How can I fix this error? 
Thank you!

**Comment by akashjobanputra** [comment]
Any updates on the issue ?

**Comment by Hosseinhashemiir** [comment]
same problem ...

**Comment by zjbabylove** [comment]
I have followed the steps,  and modify the run_checkpoint.py file 
input_node = tf.placeholder(tf.float32, shape=(None, None, None, 3), name='image')
to
input_node = tf.placeholder(tf.float32, shape=(None, 368, 432, 3), name='image')

then run:
$ python3 run_checkpoint.py --model=mobilenet

and I got en error:
InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [1,1,128,19] rhs shape= [1,1,64,19]
	 [[Node: save/Assign_293 = Assign[T=DT_FLOAT, _class=["loc:@Openpose/MConv_Stage5_L2_5_pointwise/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Openpose/MConv_Stage5_L2_5_pointwise/weights, save/RestoreV2/_587)]]
	 [[Node: save/RestoreV2/_32 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_38_save/RestoreV2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](save/RestoreV2:16)]]

how to fix this error?
