### ISSUE TITLE
Failed to retrieve a part of the model?

### ISSUE THREAD

**Issue by callemein** [ildoonet/tf-openpose#23]
I've installed all the requirements + downloaded the models using the scripts provided in each pretrained folder. The CMU model works on CPU, though the mobilenet models give this error while using the realtime_webcam.py:

`2017-11-27 00:14:10.738201: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./models/trained/mobilenet_368x368/model-release: Not found: ./models/trained/mobilenet_368x368; No such file or directory
`

**Comment by Mukei** [comment]
I have the same issue but with `'trained/mobilenet_fast/model-163000',` as I was trying to use the `mobilenet_fast` model.

```bash
InvalidArgumentError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./models/trained/mobilenet_fast/model-163000: Not found: ./models/trained/mobilenet_fast; No such file or directory
```
@ildoonet, It would be really appreciated if you could share the needed files.

**Comment by buff4life123** [comment]
duplicated https://github.com/ildoonet/tf-openpose/issues/14
the mobilenetmodel is: https://www.dropbox.com/s/09xivpuboecge56/mobilenet_0.75_0.50_model-388003.zip?dl=0

**Comment by callemein** [comment]
Hello @buff4life123 , Can you provide further explanation?

**Comment by buff4life123** [comment]
in script "networks.py"  for example I changed line 41: **'mobilenet': 'trained/mobilenet_%s/model-release' % s,**  to the path i have the mobilenet model: **'trained/model-388003',**

**Comment by Hosseinhashemiir** [comment]
@buff4life123  @ildoonet 
I downloaded the mobilenetmodel and I've put in the same directory(/models/trained/mobilenet_368x368/model-release)  but still I have this error :| 
I will be a pleasure if you help me for fix it. thanks.

> DataLossError (see above for traceback): Unable to open table file ./models/trained/mobilenet_368x368/model-release: Failed precondition: models/trained/mobilenet_368x368/model-release: perhaps your file is in a different file format and you need to use a different restore operator?
> 	 [[Node: save/RestoreV2_21 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_21/tensor_names, save/RestoreV2_21/shape_and_slices)]]
> 	 [[Node: save/RestoreV2_70/_753 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_2048_save/RestoreV2_70", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

**Comment by callemein** [comment]
@Hosseinhashemiir You should do what @buff4life123 suggested but not point to the folder where the model files are, but to the model file path without extension.

My current ./models/trained/ folder contains

```
ls models/trained/
mobilenet_0.75_0.50_model-388003.zip  model-388003.data-00000-of-00001  model-388003.index  model-388003.meta
```

@buff4life123 Thanks for the help so far! The program has been able to find my model now. Yet I've come across another error.

```

2017-11-30 08:08:48,717 INFO Restoring parameters from ./models/trained/model-388003
2017-11-30 08:09:11.706616: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key MobilenetV1/Conv2d_0/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:11.715461: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage6_L2_5_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:11.720929: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key MobilenetV1/Conv2d_10_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:11.738888: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key MobilenetV1/Conv2d_11_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:11.743781: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage6_L2_4_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:11.754175: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key MobilenetV1/Conv2d_1_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:11.762468: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key MobilenetV1/Conv2d_2_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:11.776100: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key MobilenetV1/Conv2d_3_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:11.787829: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key MobilenetV1/Conv2d_4_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:11.791907: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage6_L2_3_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:11.802478: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key MobilenetV1/Conv2d_5_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:11.815562: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key MobilenetV1/Conv2d_6_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:11.829679: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key MobilenetV1/Conv2d_7_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:11.834683: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage6_L2_2_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:11.846776: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key MobilenetV1/Conv2d_8_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:11.860074: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key MobilenetV1/Conv2d_9_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:11.877449: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage1_L1_1_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:11.880398: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage6_L2_1_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:11.888015: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage1_L1_2_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:11.900864: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage1_L1_3_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:11.911183: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage1_L1_4_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:11.917921: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage6_L1_5_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:11.923240: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage1_L1_5_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:11.942424: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage1_L2_1_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:11.952305: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage6_L1_4_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:11.954828: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage1_L2_2_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:11.962173: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage1_L2_3_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:11.980018: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage1_L2_4_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:11.991281: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage1_L2_5_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:11.994046: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage6_L1_3_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.004021: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage2_L1_1_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.020449: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage2_L1_2_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.031650: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage6_L1_2_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.034980: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage2_L1_3_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.040888: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage2_L1_4_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.056181: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage2_L1_5_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.066826: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage6_L1_1_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.068394: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage2_L2_1_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.078828: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage2_L2_2_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.087651: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage2_L2_3_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.100643: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage2_L2_4_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.103509: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage5_L2_5_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.113833: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage2_L2_5_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.127964: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage3_L1_1_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.135524: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage5_L2_4_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.142942: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage3_L1_2_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.156758: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage3_L1_3_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.170219: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage3_L1_4_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.177752: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage5_L2_3_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.189621: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage3_L1_5_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.200292: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage3_L2_1_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.214363: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage3_L2_2_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.218607: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage5_L2_2_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.229146: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage3_L2_3_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.241127: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage3_L2_4_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.251546: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage3_L2_5_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.260964: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage5_L2_1_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.262127: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage4_L1_1_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.275624: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage4_L1_2_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.286072: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage4_L1_3_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.297146: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage5_L1_5_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.300741: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage4_L1_4_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.310185: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage4_L1_5_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.328345: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage4_L2_1_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.333063: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage4_L2_2_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.342971: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage5_L1_4_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.345543: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage4_L2_3_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.356548: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage4_L2_4_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.371580: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage4_L2_5_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.380979: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage5_L1_1_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.385012: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage5_L1_3_pointwise/BatchNorm/gamma not found in checkpoint
2017-11-30 08:09:12.401797: W tensorflow/core/framework/op_kernel.cc:1152] Not found: Key Openpose/MConv_Stage5_L1_2_pointwise/BatchNorm/gamma not found in checkpoint
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/cv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1039, in _do_call
    return fn(*args)
  File "/home/pi/.virtualenvs/cv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1021, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.4/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/pi/.virtualenvs/cv/lib/python3.4/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Key MobilenetV1/Conv2d_0/BatchNorm/gamma not found in checkpoint
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "realtime_webcam.py", line 64, in <module>
    net, _, last_layer = get_network(args.model, input_node, sess)
  File "/home/pi/tf-openpose/networks.py", line 46, in get_network
    loader.restore(sess_for_load, os.path.join(_get_base_path(), ckpts[type]))
  File "/home/pi/.virtualenvs/cv/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 1457, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/pi/.virtualenvs/cv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/home/pi/.virtualenvs/cv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/home/pi/.virtualenvs/cv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/home/pi/.virtualenvs/cv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key MobilenetV1/Conv2d_0/BatchNorm/gamma not found in checkpoint
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]

Caused by op 'save/RestoreV2_1', defined at:
  File "realtime_webcam.py", line 64, in <module>
    net, _, last_layer = get_network(args.model, input_node, sess)
  File "/home/pi/tf-openpose/networks.py", line 45, in get_network
    loader = tf.train.Saver()
  File "/home/pi/.virtualenvs/cv/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 1056, in __init__
    self.build()
  File "/home/pi/.virtualenvs/cv/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 1086, in build
    restore_sequentially=self._restore_sequentially)
  File "/home/pi/.virtualenvs/cv/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/home/pi/.virtualenvs/cv/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/pi/.virtualenvs/cv/lib/python3.4/site-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/pi/.virtualenvs/cv/lib/python3.4/site-packages/tensorflow/python/ops/gen_io_ops.py", line 669, in restore_v2
    dtypes=dtypes, name=name)
  File "/home/pi/.virtualenvs/cv/lib/python3.4/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/home/pi/.virtualenvs/cv/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/pi/.virtualenvs/cv/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Key MobilenetV1/Conv2d_0/BatchNorm/gamma not found in checkpoint
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]

```

**Comment by HEUzhouhanwen** [comment]
My program also find  the model now ,thank you so much.But then I met the same error like you,have you solve it?

**Comment by izaakvc** [comment]
I had the same issue but I solved it:
1. Make sure you have the correct model unpacked in the right folder (I unpacked it to `./pretrained/mobilenet_0.75_0.50_model-388003/model-388003`)
2. Change line 41 of netwoks.py to `'mobilenet': 'pretrained/mobilenet_0.75_0.50_model-388003/model-388003',` the correct path to the unpacked network.
3. Make sure you are using tensorflow 1.3 (and NOT 1.2)!

**Comment by jhorowitz** [comment]
For those of you like me who were still confused, you're not supposed to rename the zip file, rather you're supposed to unzip it and then change the name before the extension of the data, index and meta files. If you're on a unix computer, run the commands below to make this work. No code changes required.

```bash
mkdir -p ./models/trained/mobilenet_368x368/
cd ./models/trained/mobilenet_368x368/
wget https://www.dropbox.com/s/09xivpuboecge56/mobilenet_0.75_0.50_model-388003.zip
unzip mobilenet_0.75_0.50_model-388003.zip
mv model-388003.data-00000-of-00001 model-release.data-00000-of-00001
mv model-388003.index model-release.index
mv model-388003.meta model-release.meta
```

**Comment by chriszeng87** [comment]
I did what @jhorowitz said but got this error:
2017-12-22 18:07:22.608339: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-12-22 18:07:22.608509: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-12-22 18:07:22.608516: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-12-22 18:07:22.608520: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
INFO:tensorflow:Restoring parameters from ./models/trained/mobilenet_368x368/model-release
2017-12-22 18:07:25,981 INFO Restoring parameters from ./models/trained/mobilenet_368x368/model-release
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /Users/travis/build/skvark/opencv-python/opencv/modules/imgproc/src/imgwarp.cpp, line 3483
Traceback (most recent call last):
  File "inference.py", line 38, in <module>
    image = read_imgfile(args.imgpath, args.input_width, args.input_height)
  File "/Users/qyvideo/work/deep_learning/tf-openpose/common.py", line 214, in read_imgfile
    return preprocess(val_image, width, height)
  File "/Users/qyvideo/work/deep_learning/tf-openpose/common.py", line 218, in preprocess
    val_image = cv2.resize(img, (width, height))
cv2.error: /Users/travis/build/skvark/opencv-python/opencv/modules/imgproc/src/imgwarp.cpp:3483: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize

**Comment by jhorowitz** [comment]
Looks like the error I get when it can't find the image file. Are you sure you're pointing it at a valid image?

**Comment by chriszeng87** [comment]
Yes, the image path is wrong... Thank you, I delete the thread.

**Comment by jhorowitz** [comment]
@chriszeng87 Other people will probably have the same issue and reading the thread will probably help them. Please don't delete it.

**Comment by sunnyheart008205** [comment]
@callemein Hi, I  have the problem you met, and don't know what to do. (My tensorflow version is 1.30). I want to know how you fix it. Thanks!

**Comment by andyqian2015** [comment]
@jhorowitz , sorry to intrupt you. do you know where to get the fast_mobilenet's model? I check,and canot find it . the github hasn't afforded link to download .

**Comment by andyqian2015** [comment]
@Mukei ,where do you get the file of mobilenet_fast/model-163000,can you give me some clue ?

**Comment by chriszeng87** [comment]
@andyqian2015 I think @ildoonet did not release it, so you should train it by yourself? Hope someone can tell me that I'm wrong.

**Comment by andyqian2015** [comment]
thx for you reply @chriszeng87 , now I am trying to train the MobileNet_fast from the scratch.

**Comment by xxxyyyzzzz** [comment]
Hi @andyqian2015, does the above comment means that @ildoonet doesnt share mobilenet_fast or he doesnt share all the 3 models? So, I need to train from scratch! 
Can anyone make it clear..
Thanks in advance

**Comment by chriszeng87** [comment]
@xxxyyyzzzz In Chinese, we have a saying: do it yourself and you will get ample food and clothing.
