### ISSUE TITLE
Test inference is not very good

### ISSUE THREAD

**Issue by felixfuu** [ildoonet/tf-openpose#3]
![20171009175459](https://user-images.githubusercontent.com/30679630/31332993-149bec84-ad1b-11e7-97f3-b1505795a090.png)  I run the inference.py and use the ./models/numpy/openpose_coco.npy to get this result, as you say ,you converted the model from openpose,but why the result is different from openpose?Is there something differences between your project and the original openpose?

**Comment by felixfuu** [comment]
i found the reason,there is a bug in your code.Line 59 inference.py you should modify it to image = image/256 - 0.5

**Comment by ildoonet** [comment]
@felixfuu 

Nice catch. I also work on post-processing which have few bugs.

I'm training networks with different settings now, If this work is done, I will spend more time on the inference-related codes. Please wait.

Thanks.

**Comment by felixfuu** [comment]
@ildoonet how can i test you mobilenet model? can you share you pretrained pose based on mobilenet?

**Comment by ildoonet** [comment]
@felixfuu 

I'm training the model now, 

since it has fewer number of parameters, it doesn't reach the performance of the original one. 

So i'm trying to improve it now.

**Comment by felixfuu** [comment]
@ildoonet  When i trained the pose, I met a problem：
Process _Worker-31:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/dataflow/prefetch.py", line 149, in run
    for dp in self.ds.get_data():
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/dataflow/common.py", line 263, in get_data
    for dp in self.ds.get_data():
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/dataflow/common.py", line 263, in get_data
    for dp in self.ds.get_data():
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/dataflow/common.py", line 263, in get_data
    for dp in self.ds.get_data():
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/dataflow/common.py", line 263, in get_data
    for dp in self.ds.get_data():
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/dataflow/common.py", line 263, in get_data
    for dp in self.ds.get_data():
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/dataflow/common.py", line 263, in get_data
    for dp in self.ds.get_data():
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/dataflow/common.py", line 263, in get_data
    for dp in self.ds.get_data():
  File "/proj/tf-openpose/pose_dataset.py", line 292, in get_data
    datum.ParseFromString(s)
TypeError: a bytes-like object is required, not 'NoneType'
Process _Worker-26:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap

can you @ildoonet  give me some advice about this?

**Comment by felixfuu** [comment]
Also,the mobilenet model  that you shared doesn't match the code in def get_network(): 
log info:   Key Openpose/MConv_Stage1_L1_1_pointwise/BatchNorm/gamma n
ot found in checkpoint

**Comment by ildoonet** [comment]
@felixfuu This problem was fixed with some other commits.. You should not see this again.
